name: kitctl-bootstrap-workflow
on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]
  workflow_dispatch: {}
jobs:  
  build-cli:
    strategy:
      matrix:
        os: ["darwin", "linux"]
        arch: ["amd64"]
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       contents: read 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin/
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::078365735624:role/github-Token-generate
          role-session-name: samplerolesession
          aws-region: us-west-2 
    - name: Build the KIT CLI
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./bin/kitctl ./cmd/kitctl/ 
        chmod +x ./bin/kitctl
        pwd
      working-directory: substrate
    - name: Print binary location
      run: |
           echo "Binary location: $(pwd)/substrate/bin/kitctl"
           cd /home/runner/work/kubernetes-iteration-toolkit/kubernetes-iteration-toolkit/substrate/cmd/kitctl
           ls
   
          

   
